import { CurrencyInfo } from "@/context/modal-context";

export const currencyData: CurrencyInfo[] = [
  {
    name: "United States Dollar",
    code: "USD",
    sign: "$",
    locale: "en-US",
    symbolPosition: "before",
    country: "United States",
    exchangeRate: 1.0,
    flag: "🇺🇸",
    timezone: "America/New_York",
    currencyColor: "#1a1a1a"
  },
  {
    name: "Euro",
    code: "EUR",
    sign: "€",
    locale: "en-DE",
    symbolPosition: "before",
    country: "Eurozone",
    exchangeRate: 0.85,
    flag: "🇪🇺",
    timezone: "Europe/Berlin",
    currencyColor: "#0099cc"
  },
  {
    name: "British Pound",
    code: "GBP",
    sign: "£",
    locale: "en-GB",
    symbolPosition: "before",
    country: "United Kingdom",
    exchangeRate: 0.73,
    flag: "🇬🇧",
    timezone: "Europe/London",
    currencyColor: "#bf5a15"
  },
  {
    name: "Japanese Yen",
    code: "JPY",
    sign: "¥",
    locale: "ja-JP",
    symbolPosition: "before",
    country: "Japan",
    exchangeRate: 109.29,
    flag: "🇯🇵",
    timezone: "Asia/Tokyo",
    currencyColor: "#d81b60"
  },
  {
    name: "Canadian Dollar",
    code: "CAD",
    sign: "CA$",
    locale: "en-CA",
    symbolPosition: "before",
    country: "Canada",
    exchangeRate: 1.27,
    flag: "🇨🇦",
    timezone: "America/Toronto",
    currencyColor: "#ff6600"
  },
  {
    name: "Australian Dollar",
    code: "AUD",
    sign: "A$",
    locale: "en-AU",
    symbolPosition: "before",
    country: "Australia",
    exchangeRate: 1.31,
    flag: "🇦🇺",
    timezone: "Australia/Sydney",
    currencyColor: "#009688"
  },
  {
    name: "Swiss Franc",
    code: "CHF",
    sign: "CHF",
    locale: "de-CH",
    symbolPosition: "before",
    country: "Switzerland",
    exchangeRate: 0.92,
    flag: "🇨🇭",
    timezone: "Europe/Zurich",
    currencyColor: "#4caf50"
  },
  {
    name: "Chinese Yuan",
    code: "CNY",
    sign: "¥",
    locale: "zh-CN",
    symbolPosition: "before",
    country: "China",
    exchangeRate: 6.44,
    flag: "🇨🇳",
    timezone: "Asia/Shanghai",
    currencyColor: "#e91e63"
  },
  {
    name: "Indian Rupee",
    code: "INR",
    sign: "₹",
    locale: "en-IN",
    symbolPosition: "before",
    country: "India",
    exchangeRate: 74.38,
    flag: "🇮🇳",
    timezone: "Asia/Kolkata",
    currencyColor: "#ff5722"
  },
  {
    name: "Brazilian Real",
    code: "BRL",
    sign: "R$",
    locale: "pt-BR",
    symbolPosition: "before",
    country: "Brazil",
    exchangeRate: 5.37,
    flag: "🇧🇷",
    timezone: "America/Sao_Paulo",
    currencyColor: "#795548"
  },
  {
    name: "Russian Ruble",
    code: "RUB",
    sign: "₽",
    locale: "ru-RU",
    symbolPosition: "before",
    country: "Russia",
    exchangeRate: 76.48,
    flag: "🇷🇺",
    timezone: "Europe/Moscow",
    currencyColor: "#607d8b"
  },
  {
    name: "South African Rand",
    code: "ZAR",
    sign: "R",
    locale: "en-ZA",
    symbolPosition: "before",
    country: "South Africa",
    exchangeRate: 15.19,
    flag: "🇿🇦",
    timezone: "Africa/Johannesburg",
    currencyColor: "#ff9800"
  },
  {
    name: "Singapore Dollar",
    code: "SGD",
    sign: "S$",
    locale: "en-SG",
    symbolPosition: "before",
    country: "Singapore",
    exchangeRate: 1.33,
    flag: "🇸🇬",
    timezone: "Asia/Singapore",
    currencyColor: "#009688"
  },
  {
    name: "New Zealand Dollar",
    code: "NZD",
    sign: "NZ$",
    locale: "en-NZ",
    symbolPosition: "before",
    country: "New Zealand",
    exchangeRate: 1.4,
    flag: "🇳🇿",
    timezone: "Pacific/Auckland",
    currencyColor: "#4caf50"
  },
  {
    name: "Hong Kong Dollar",
    code: "HKD",
    sign: "HK$",
    locale: "en-HK",
    symbolPosition: "before",
    country: "Hong Kong",
    exchangeRate: 7.75,
    flag: "🇭🇰",
    timezone: "Asia/Hong_Kong",
    currencyColor: "#e91e63"
  },

  {
    name: "Swedish Krona",
    code: "SEK",
    sign: "kr",
    locale: "sv-SE",
    symbolPosition: "after",
    country: "Sweden",
    exchangeRate: 8.51,
    flag: "🇸🇪",
    timezone: "Europe/Stockholm",
    currencyColor: "#673ab7"
  },
  {
    name: "Turkish Lira",
    code: "TRY",
    sign: "₺",
    locale: "tr-TR",
    symbolPosition: "before",
    country: "Turkey",
    exchangeRate: 13.4,
    flag: "🇹🇷",
    timezone: "Europe/Istanbul",
    currencyColor: "#ff5722"
  },
  {
    name: "South Korean Won",
    code: "KRW",
    sign: "₩",
    locale: "ko-KR",
    symbolPosition: "before",
    country: "South Korea",
    exchangeRate: 1159.02,
    flag: "🇰🇷",
    timezone: "Asia/Seoul",
    currencyColor: "#cddc39"
  },
  {
    name: "Saudi Riyal",
    code: "SAR",
    sign: "﷼",
    locale: "ar-SA",
    symbolPosition: "after",
    country: "Saudi Arabia",
    exchangeRate: 3.75,
    flag: "🇸🇦",
    timezone: "Asia/Riyadh",
    currencyColor: "#4caf50"
  },
  {
    name: "Bangladeshi Taka",
    code: "BDT",
    sign: "৳",
    locale: "en-BD",
    symbolPosition: "after",
    country: "Bangladesh",
    exchangeRate: 85.01,
    flag: "🇧🇩",
    timezone: "Asia/Dhaka",
    currencyColor: "#ff6600"
  }
];
